### ISSUE TITLE
'PIN_MAP' was not declared in this scope

### ISSUE THREAD

**Issue by dresslerc** [technobly/SparkCore-NeoPixel#12]
Veryfing code using this library in Particle Build fails with this error:
```
neopixel/neopixel.cpp:110:9: error: 'PIN_MAP' was not declared in this scope
         PIN_MAP[pin].gpio_peripheral->BSRR = PIN_MAP[pin].gpio_pin

**Comment by technobly** [comment]
Thanks! Fixed a while ago :)

**Comment by gotnull** [comment]
Still not fixed..

**Comment by sammysawdust** [comment]
Sorry, seeing this too.
neopixel/neopixel.cpp: In member function 'void Adafruit_NeoPixel::show()':
This looks like an error in neopixel library. Would you like to create an issue on GitHub to let the author know?
CREATE ISSUE
neopixel/neopixel.cpp:92:9: error: 'PIN_MAP' was not declared in this scope
         PIN_MAP[pin].gpio_peripheral->BSRR = PIN_MAP[pin].gpio_pin; // HIGH
         ^

**Comment by technobly** [comment]
@gotnull  @sammysawdust please either remove and re-add the library to your existing app, or create a new app and add the library again, or use one of the existing examples for the latest version.

If all of those fail for you, please let me know what Device and version you are compiling with, and let's see your source code.  Thanks!

**Comment by gotnull** [comment]
That worked, thanks.

On Thursday, 17 March 2016, Technobly <notifications@github.com> wrote:

> @gotnull <https://github.com/gotnull> @sammysawdust
> <https://github.com/sammysawdust> please either remove and re-add the
> library to your existing app, or create a new app and add the library
> again, or use one of the existing examples for the latest version.
>
> If all of those fail for you, please let me know what Device and version
> you are compiling with, and let's see your source code. Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/technobly/SparkCore-NeoPixel/issues/12#issuecomment-197718078>
>


-- 
Sent from my iPhone (apologies for any typos or brevity).

**Comment by technobly** [comment]
Good to hear!
