### ISSUE TITLE
Particle P1 is not yet supported

### ISSUE THREAD

**Issue by zzhang1** [technobly/SparkCore-NeoPixel#14]
The Photon P1 is currently unsupported. Compiling returns the error: "*** PLATFORM_ID not supported by this library. PLATFORM should be Core or Photon ***".

Adding the Photon's pinHI and pinLO definitions under a new tag does not help:
#elif PLATFORM_ID == 8
...

This lets the code compile, but the P1 fails to send a proper signal to the NeoPixels strip.

**Comment by zzhang1** [comment]
Meanwhile, this can trivially be fixed by changing the #if PLATFORM_ID == 6 to support PLATFORM_ID 8 throughout neopixel.cpp.

**Comment by technobly** [comment]
Solved with PR #15
