### ISSUE TITLE
redefinition of 'STM32_Pin_Info* PIN_MAP'

### ISSUE THREAD

**Issue by Theamazingarnaud** [technobly/SparkCore-NeoPixel#18]
Veryfing code using this library in Particle Build fails with this error:
```
neopixel/neopixel.cpp:57:19: error: redefinition of 'STM32_Pin_Info* PIN_MAP'
   STM32_Pin_Info* PIN_MAP = HAL_Pin_Map()

**Comment by technobly** [comment]
Try removing the library, and re-adding.  That issue was fixed in the last update a while back.  I'm guessing it's an older app that you are compiling with newer v0.4.7 firmware?

**Comment by charliegerard** [comment]
Had the same issue and just tried this solution, works fine for me :)
