### ISSUE TITLE
PIN_MAP[pin] error

### ISSUE THREAD

**Issue by cbnatrix** [technobly/SparkCore-NeoPixel#22]
neopixel/neopixel.cpp:92:9: error: 'PIN_MAP' was not declared in this scope
         PIN_MAP[pin].gpio_peripheral->BSRR = PIN_MAP[pin].gpio_pin; // HIGH

The NeoPixel library has worked flawlessly for me until today.

**Comment by nicjansma** [comment]
Same here...

**Comment by technobly** [comment]
@cbnatrix @nicjansma please either remove and re-add the library to your existing app, or create a new app and add the library again, or use one of the existing examples for the latest version.

If all of those fail for you, please let me know what Device and version you are compiling with, and let's see your source code. Thanks!

**Comment by jstockdale** [comment]
I have no idea if it works on a Core but for the Photon, P1, and Electron use:

```
#elif (PLATFORM_ID == 6) || (PLATFORM_ID == 8) || (PLATFORM_ID == 10) // Photon (6) or P1 (8) or Electron (10)
  #define pinLO(_pin) pinResetFast(_pin)
  #define pinHI(_pin) pinSetFast(_pin)
#else
```

**Comment by technobly** [comment]
Closing due to no reply... this issue is typically because of an old library version compiling with newer system firmware that doesn't support `PIN_MAP` on anything except the Spark Core.  Please see my comment above if you end up here ;-)
