### ISSUE TITLE
expected identifier before numeric constant

### ISSUE THREAD

**Issue by loonylion** [technobly/SparkCore-NeoPixel#28]
Veryfing code using this library in Particle Build fails with this error:
```
neopixel/neopixel.h:60:18: error: expected identifier before numeric constant
 #define TM1829   0x04 // 800 KHz datastream ()
                  ^
```

there's a dozen of these errors, one for every chipset definition by the looks of it

**Comment by technobly** [comment]
@loonylion I'm not sure why you are seeing that error.  Is that an old app you had or a brand new one with a new copy of the NeoPixel library?

In parallel, please try to load the latest version of the NeoPixel library here (v009):
https://build.particle.io/libs/5756121cd100a78a5a00067a/tab/a-rainbow.cpp

Click on the a-rainbow.cpp file

Click the USE THIS EXAMPLE button on the left

Wait a little bit for the server to properly copy the library in the background before you compile.  If you get any error regarding `neopixel/neopixel.h` was not found, just wait a bit and try again.  After everything is ready in the background it will compile.  Just verified this right now.

---

If you continue having this issue, please post your code on the community here:
https://community.particle.io
