### ISSUE TITLE
application.h missing

### ISSUE THREAD

**Issue by hosadoya** [technobly/SparkCore-NeoPixel#33]
Getting this error after including
#include <neopixel.h>

In file included from \Documents\Arduino\Stm32Blink\Stm32Blink.ino:1:0:

\Documents\Arduino\libraries\SparkCore-NeoPixel/neopixel.h:56:25: fatal error: application.h: No such file or directory

 #include "application.h"

                         ^

compilation terminated.

exit status 1
Error compiling for board Generic STM32F103C series.

**Comment by technobly** [comment]
are you compiling this locally for the Photon or Arduino?

**Comment by technobly** [comment]
@hosadoya if you are using the Arduino, you'll want this library: https://github.com/adafruit/Adafruit_NeoPixel

**Comment by hosadoya** [comment]
I was compiling in Arduino IDE, but for STM32F103C MCU. I was using the library you mentioned, but Atmega328p MCU didn't have enough SRAM to handle the large matrix I had.
Looks like we need to port Adafruit_NeoPixel library to here:
https://github.com/rogerclarkmelbourne/Arduino_STM32/tree/master/STM32F1/libraries

I was hoping that your library would work as both Spark Core, and STM32F103C are using the same CPU: ARM 32-bit Cortex M3.
