### ISSUE TITLE
Removing Copy Ctor?

### ISSUE THREAD

**Issue by bradysalz** [technobly/SparkCore-NeoPixel#34]
This PR #31 removes the copy ctor to prevent errors when going out of scope as the object's `pixels` property gets freed. However, this breaks many of the examples. 

`Adafruit_NeoPixel strip = Adafruit_NeoPixel(PIXEL_COUNT, PIXEL_PIN, PIXEL_TYPE);`

Uses the copy ctor to initialize. I would recommend changing the examples to something like

`Adafruit_NeoPixel strip(PIXEL_COUNT, PIXEL_PIN, PIXEL_TYPE);`

Or undoing the latest PR and fixing the memory problems manually.

**Comment by nrobinson2000** [comment]
I experienced a problem as well, and I had to change my code to use:
```
Adafruit_NeoPixel strip(PIXEL_COUNT, PIXEL_PIN, PIXEL_TYPE);
```

Maybe you could make a pull request changing the examples?

**Comment by zacnelson** [comment]
I ran into this issue today as well. Modified my code per @nrobinson2000 and @bradysalz and now compiling successfully.
